In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud,STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import re,string,unicodedata
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score
from sklearn.model_selection import train_test_split
from string import punctuation
from nltk import pos_tag
from nltk.corpus import wordnet
import re
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r'C:\Users\Edna\Documents\GitHub\Haile_Resort_Sentiment_Analysis\data\processed\Haile_and_kaggledata.csv')
#df['Sentiment'].value_counts()
df['Sentiment'].value_counts()

Sentiment
Positive    9191
Negative    1240
Neutral      187
Name: count, dtype: int64

Feature Engineering

In [4]:
# Mapping sentiment to numerical labels
label_mapping = {
    'Positive': 1,
    'Negative': 0,
    'Neutral': 2
}
df['Label'] = df['Sentiment'].map(label_mapping)

df[['Sentiment','Label']]

      Sentiment  Label
0      Positive      1
1      Positive      1
2      Positive      1
3      Positive      1
4      Positive      1
...         ...    ...
10613  Positive      1
10614  Positive      1
10615  Positive      1
10616  Positive      1
10617  Positive      1

[10618 rows x 2 columns]

In [9]:
df[['Sentiment','Label']].tail(30)

      Sentiment  Label
10588  Positive      1
10589  Positive      1
10590  Positive      1
10591  Positive      1
10592  Positive      1
10593  Negative      0
10594  Positive      1
10595  Positive      1
10596  Positive      1
10597  Negative      0
10598  Positive      1
10599  Positive      1
10600  Positive      1
10601  Positive      1
10602  Positive      1
10603  Positive      1
10604  Positive      1
10605  Positive      1
10606  Positive      1
10607  Positive      1
10608  Positive      1
10609   Neutral      2
10610  Positive      1
10611  Positive      1
10612  Positive      1
10613  Positive      1
10614  Positive      1
10615  Positive      1
10616  Positive      1
10617  Positive      1